### ISSUE TITLE
Issue with Safari

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar-ui-qmediaplayer#104]
Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. when using
```
this.$refs.myPlayer.play()

```

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 13.0.4

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone6 and iPhone XR
 - OS: [e.g. iOS8.1] 12.4
 - Browser [e.g. stock browser, safari] safari

**Additional context**

**Comment by hawkeye64** [comment]
> NotAllowedError
> possibly because the user denied permission

Nothing can be done if the User denied permission.

**Comment by hawkeye64** [comment]
One thing comes to mind. A lot of browser, mobile in particular, will not all programmatically playing media or sound. It has to be associated with a user initiated click (you can't send click event to button and make it work, the browser knows). You have about 125ms after a user initiated click to play the video/sound.
