### ISSUE TITLE
Cannot read property 'play' 

### ISSUE THREAD

**Issue by diadal** [quasarframework/quasar-ui-qmediaplayer#105]
where in `config.xml` will I add this `<preference name="AllowInlineMediaPlayback" value="true" />` because am getting this error `TypeError: Cannot read property 'play' of undefined` when I do this `this.$refs.myPlayer.play()`

<img width="792" alt="Screenshot 2020-02-15 at 07 42 36" src="https://user-images.githubusercontent.com/19895516/74583414-2705d000-4fc7-11ea-82c2-9462729a33af.png">

**Describe the bug**
**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone XR Simulator
 - OS: [e.g. iOS8.1] iOS 12

**Additional context**

**Comment by hawkeye64** [comment]
@diadal is `this.$refs.myPlayer.$media` also undefined?
I don't have experience with iOS and that was a contribution from a user, so I can't really help you there. However, it must be available with Google or at least Apple developer docs.
If you do find out, please PR the docs to make them a bit better. I would appreciate it. :heart:

**Comment by diadal** [comment]
this fix my issue 

```

async playAudio () {
      try {
        await this.$refs.myPlay.play()
      } catch (err) {
        console.log(err)
      }
    }

```
