### ISSUE TITLE
Could $emit.timeupdate return tenths of second

### ISSUE THREAD

**Issue by birchb** [quasarframework/quasar-ui-qmediaplayer#108]
**Is your feature request related to a problem? Please describe.**

For use in my code, the option to return tenths of seconds on $emit.timeupdate would be helpful

**Describe the solution you'd like**

$emit.timeupdate would return 10th of seconds or exact $mediaPlayer.currentTime

**Describe alternatives you've considered**

I previously edited setCurrentTime() but it doesn't seem to return 10ths anymore.

'''
      setCurrentTime (seconds) {
        if (this.state.playReady) {
          if (this.$media && isFinite(this.$media.duration) && seconds >= 0 && seconds <= this.$media.duration) {
            this.state.currentTime = Math.floor(seconds * 10) / 10
            this.$media.currentTime = Math.floor(seconds * 10) / 10
          }
        }
      },
'''

**Additional context**

**Comment by hawkeye64** [comment]
fix will be in v1.0.20
