### ISSUE TITLE
Please add story mode like Instagram stories player.

### ISSUE THREAD

**Issue by rashidpathiyil** [quasarframework/quasar-ui-qmediaplayer#109]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want this player for showing stories.
The player never shows any play button.
When touch and hold on the screen, the video should pause, play on remove holding.
When we tap or click on the left or right sides of the screen to go previous or next videos

**Describe alternatives you've considered**
Please create a demo for this the story mode

**Additional context**
Please check Youtube/WhatsApp/Instagram stories.

**Comment by hawkeye64** [comment]
@rashidpathiyil I can add a property to hide the regular play button. There is a property to now show the Big Play button. Everything else you suggest, can be in dev-land by handling mouse clicks and getting position. Aside from hiding the play button, is there anything else you need?

**Comment by hawkeye64** [comment]
I have added property `hide-play-btn`, v1.0.21 - if you need anything else, let me know. Thanks.
