### ISSUE TITLE
UMD installation - icons missing

### ISSUE THREAD

**Issue by vibrantBits** [quasarframework/quasar-ui-qmediaplayer#110]
**Describe the bug**
I installed the plugin using UMD, which is undocumented. All worked fine except that icons are missing and I can see these errors in the console:

- QMediaPlayer: no icon set loaded called 'material-icons'
- Be sure to load the UMD version of the icon set in a script tag before using with UMD

**To Reproduce**
Installed like this:
`<head>`
  `<!-- AFTER the Quasar stylesheet tags: -->`
    `<link href="https://cdn.jsdelivr.net/npm/@quasar/quasar-ui-qmediaplayer@1.0.20/dist/index.min.css" rel="stylesheet" type="text/css">`
`</head>`
`<body>`
  `<!-- at end of body, AFTER Quasar script(s): -->`
   `<script src="https://cdn.jsdelivr.net/npm/@quasar/quasar-ui-qmediaplayer@1.0.20/dist/index.umd.min.js"></script>`
`</body>`

Then just insert the code as in the Demo.

**Expected behavior**
Video player should show control icons

**Screenshots**
![image](https://user-images.githubusercontent.com/3849951/77127230-5ae27400-6a11-11ea-8667-cde9a2c49fee.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by hawkeye64** [comment]
UMD is documented here: https://github.com/quasarframework/quasar-ui-qmediaplayer/tree/dev/ui#umd-variant

Here is UMD on codepen: https://codepen.io/Hawkeye64/pen/WNNgdYa

**Comment by hawkeye64** [comment]
For UMD, you will need to also use icon and language packs, ie:
https://cdn.jsdelivr.net/npm/@quasar/quasar-ui-qmediaplayer@latest/dist/icon-set/material-icons.umd.js
https://cdn.jsdelivr.net/npm/@quasar/quasar-ui-qmediaplayer@latest/dist/lang/en-us.umd.js
