### ISSUE TITLE
VAST support

### ISSUE THREAD

**Issue by altezza04** [quasarframework/quasar-ui-qmediaplayer#117]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Would like a option to add VAST Ad support to the player

**Describe alternatives you've considered**
May be a tutorial on how to add VAST js on the player?

**Comment by hawkeye64** [comment]
@altezza04 Sorry, I don't know what VAST is. However, the `overlay` slot was creaed so developers can do whatever they want. You can use this slot to add items to the display. From ads to a carousel of videos to pick from (like Youtube or Netflix style).

**Comment by altezza04** [comment]
Ok. thanks, will try to do that. VAST is a standard format for pre-roll video ad display (ad. video play before your video), it common for monetization video content for Google Ad. Sense

https://www.iab.com/guidelines/digital-video-ad-serving-template-vast/
https://github.com/dailymotion/vast-client-js
https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector?hl=zh-tw

**Comment by hawkeye64** [comment]
Ah, you mean like Youtube showing ads once in a while and then after 5 seconds (sometimes), the "Skip Ad" button?
You can do all this with QMediaPlayer using `source` property and `overlay` slot.

**Comment by isilta** [comment]
Can you give any example?
What should I do If I want to exoclick's vast

**Comment by gokaybiz** [comment]
Can you give any example?
What should I do If I want to exoclick's vast

**Comment by hawkeye64** [comment]
@gokaybiz At this point in time I do not have time to give an example. Sorry. I am just a little overwhelmed these days.
