### ISSUE TITLE
How to enable DASH?

### ISSUE THREAD

**Issue by francoism90** [quasarframework/quasar-ui-qmediaplayer#118]
**Is your feature request related to a problem? Please describe.**
DASH/HLS is used a lot nowadays, is it supported?

**Describe the solution you'd like**
I tried to load a dash file, but it doesn't open it.

**Describe alternatives you've considered**
I'm using shakajs at the moment. MediaElement supports HLS/DASH nowadays as well.

**Additional context**
I'm confused, isn't this based on MediaElement.js?

**Comment by hawkeye64** [comment]
@francoism90 No, not `MediaElement.js` - [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement)

If you see that HTMLMediaElement supports Dash, let me know.

**Comment by francoism90** [comment]
@hawkeye64 Oops! Sorry!
