### ISSUE TITLE
Full screen mode shows right scroll bar

### ISSUE THREAD

**Issue by Rackar** [quasarframework/quasar-ui-qmediaplayer#121]
**Describe the bug**
Full screen mode shows right scroll bar, and cover on the video

**To Reproduce**
click full screen button

**Screenshots**
![image](https://user-images.githubusercontent.com/18388400/80863470-2b30b800-8caf-11ea-8195-b5ec697760fa.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by hawkeye64** [comment]
Did it actually go into fullscreen mode, or just full-window mode? If the latter, make sure your have the quasar plug-in `AppFullscreen` installed in your quasar.conf.js

**Comment by Rackar** [comment]
Yes, it's fullscreen.
![quasar2](https://user-images.githubusercontent.com/18388400/81252597-e1eaba80-9058-11ea-9e2c-71959a9c0637.gif)

**Comment by hawkeye64** [comment]
Thanks for the info. I see what's happening and will have to investigate. It might take a few days as I have seasonal sickness.

**Comment by hawkeye64** [comment]
@Rackar I have a potential fix. Will do further testing. Will likely release tomorrow. And, thanks for bringing this to my attention. :heart:

**Comment by Rackar** [comment]
@hawkeye64 Thank you. Wish you get better soon.

**Comment by hawkeye64** [comment]
@Rackar Released with v1.0.24
