### ISSUE TITLE
incorrect background-color

### ISSUE THREAD

**Issue by mentalmap** [quasarframework/quasar-ui-qmediaplayer#133]
**Describe the bug**
```html
<div id="q-app">
  <div style="max-width: 800px; width: 100%;">
    <q-media-player
      type="audio"
      :sources="sources"
      background-color="red"
    ></q-media-player>
  </div>
</div>
```

**To Reproduce**
https://codepen.io/mentalmap/pen/WNrpjQK

**Expected behavior**
From https://quasar.dev/style/color-palette
![image](https://user-images.githubusercontent.com/1574662/85222687-d75d6800-b3ef-11ea-8262-55a6dd5adea2.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/1574662/85222665-9e24f800-b3ef-11ea-8be1-64935b35ad60.png)

**Comment by m0jimo** [comment]
Colour si correct but controls have transparency, so the red colour is behind. Try to change the type to video and you will see the requested color.
I’d vote for adding a color for control panel :-).

**Comment by hawkeye64** [comment]
@m0jimo Add issue if you think it makes sense

**Comment by mentalmap** [comment]
Thanks.

```sass
.q-media
  &__controls
    background: transparent
```
