### ISSUE TITLE
hide volume button

### ISSUE THREAD

**Issue by mentalmap** [quasarframework/quasar-ui-qmediaplayer#134]
found hide-volume-slider setting, but no hide-volume-btn setting

![image](https://user-images.githubusercontent.com/1574662/85223162-3b356000-b3f3-11ea-9ebd-5eeff8dbc76d.png)

**Comment by hawkeye64** [comment]
There is also `hide-play-btn`
I will look into adding more ability to hide various controls

**Comment by hawkeye64** [comment]
Fixed in v1.1.0
