### ISSUE TITLE
Safari & IE11 Issues

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qmediaplayer#142]
**Describe the bug**
When testing new feature `no-controls-overlay` (I'll PR in a few days) mode I'd like to document following issues related to the current player version.

**To Reproduce**
The best is to use [live demo](https://quasarframework.github.io/quasar-ui-qmediaplayer/demo) with single video on the page
**Safari iPad + Safari iMac** (iPhone show only native controls panel):
1. Play a video 
2. Once the video is played control panel nor big play button is visible. Click on the video to toggle play/pause (it looks like that animation height for controls + missing z-index: ~~6000~~ for controls is causing the issue)
3. Big play button is not visible (needs z-index: ~~6000~~)
---
1. Before starting the video (iPad portrait mode) switch to fullscreen
2. There are no controls in fullscreen. When you use gesture to go back from fullscreen video disappears from the page (could be related to auto height) 

Other issues
- Firefox - doesn't support .mp4, .mp3 (nothing can be played from examples page)
- IE11 - doesn't play .mp3 audio (must be AAC)
- IE11 - cursor has caret when mouse over a bigPlayButton
- IE11 - QBtn icons are align to the right edge of button (related to min/max width of buttons - ~~fix will be part of `no-controls-overlay`~~. 
- Poster works only if the video start time is at time 00:00

**Expected behavior**
The same behavior in all modern browsers (ok IE is not modern but can be handy to work somehow)

**Desktop (please complete the following information):**
 see above
**Smartphone (please complete the following information):**
 - Devices: iPhone6s, iMac 2010, Firefox + IE11 on Windows 10
I haven't tried Android, yet.

**Additional context**
I tried to find fixes for issues described above but it is more challenging than it appears. Fix for one browser always breaks st. else :-).

**Comment by hawkeye64** [comment]
@m0jimo Thanks for all of this and taking it on. I am going for 8 days vacation, starting tomorrow. If you need anything tho, let me know and I'll try to respond. We're going off-grid, and sometimes we do get a signal.

**Comment by m0jimo** [comment]
Enjoy vacation without IT equipment. I've pushed changes related to Safari and half-baked 'no-controls-overlay' will come with inline comments later. Now I can see how much work is behind the qMediaPlayer and what has to be taken in account to work it properly.

**Comment by hawkeye64** [comment]
> IE11 - cursor has caret when mouse over a bigPlayButton

I think I fixed this but forgot to put it in release notes for v1.0.28 release
