### ISSUE TITLE
IE11 - Qbtn size

### ISSUE THREAD

**Issue by m0jimo** [quasarframework/quasar-ui-qmediaplayer#144]
**Describe the bug**
IE11 shows `Qbtn` (with limited width) icons aligned to the right edge.

**To Reproduce**
Open [demo page](https://quasarframework.github.io/quasar-ui-qmediaplayer/demo) in IE11.

**Expected behavior**
Icons should be in the center as in other modern browser
![image](https://user-images.githubusercontent.com/37825539/85987879-8c92b000-b9ee-11ea-90a8-8d0ed7e51906.png)

**Screenshots IE11**
![image](https://user-images.githubusercontent.com/37825539/85987092-79cbab80-b9ed-11ea-9398-5e586ec8ee55.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Internet Explorer 11

**Additional context**
Problem is caused by settings a 
![image](https://user-images.githubusercontent.com/37825539/85987329-cadb9f80-b9ed-11ea-90a1-17f79cc4535d.png)
If the min/max button width is removed result is OK but the buttons are too wide everywhere.
![image](https://user-images.githubusercontent.com/37825539/85987704-48071480-b9ee-11ea-84d4-e3de04f72637.png)
 
Would be nice to fix it but I think its not a big deal for the future as IE11 is slowly leaving a position for other modern browsers.
I know it is partly related to Quasar component, so maybe to post this issue/question to Quasar issue tracker/Discord?

**Comment by pdanpdan** [comment]
If the button has a `padding="4px"` it should work everywhere.

**Comment by hawkeye64** [comment]
Fixed in v1.0.27
