### ISSUE TITLE
Module missing in ssr build

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar-ui-qmediaplayer#146]
- quasar ext add @quasar/qmediaplayer
- quasar build -m ssr --debug
- copy ssr folder from /dist to production system (no quasar folder)
- npm install in the ssr folder on target system
- npm run start
- "Server listening on port 3000"
- Try to access site
- Http 500, debug says: "cannot find module ‘@quasar/quasar-ui-qmediaplayer"

Am I missing something here?

**Comment by hawkeye64** [comment]
@lmfmaier I am not sure why this is happening to you. As you can see, the app-ext has `quasar-ui-qmediaplayer` as a dep, not a devDep
```js
  "dependencies": {
    "@quasar/quasar-ui-qmediaplayer": "^1.0.26"
  },
```
I am using this at work and not having an issue like this. The only thing I can think of is that you are using npm and not yarn. Npm has known issues hoisting children dependencies.

**Comment by lmfmaier** [comment]
Thanks, I already noticed that it is included only in dev dependecies, but I thought "quasar build" will probably handle this. Time to switch to yarn i guess

**Comment by hawkeye64** [comment]
This could be because Quasar installs apps in devDeps. You could try moving it manually to deps and then reinstall.

**Comment by lmfmaier** [comment]
I did that and it works. Thank you!

**Comment by hawkeye64** [comment]
@lmfmaier Perfect! Thanks for letting me know! :+1:
