### ISSUE TITLE
Html5 <video> not working

### ISSUE THREAD

**Issue by WaldemarKarasik** [quasarframework/quasar-ui-qmediaplayer#206]
**Describe the bug**
Html5 video element not playing videos

**Codepen/jsFiddle/Codesandbox (required)**
Fork a Codepen (https://codepen.quasar.dev) or a jsFiddle (https://jsfiddle.quasar.dev) or a Codesandbox (https://codesandbox.quasar.dev) and hit save then copy-paste link here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information):**
OS:
Node:
NPM:
Yarn:
Browsers:
iOS:
Android:
Electron:

**Additional context**
https://github.com/quasarframework/quasar-ui-qmediaplayerIn 
This plugin plays videos that native html5 video element doesn't.  Html5 video element  plays neither mp4 nor m3u8(with hls.js)
It's definitely Quasar's fault as in Angular it works fine with the same video source

**Comment by hawkeye64** [comment]
@WaldemarKarasik 
> Html5 video element not playing videos

I am closing this. Feel free to open using the issue template which will ask you for more information.
