### ISSUE TITLE
Get the movie link from computed property

### ISSUE THREAD

**Issue by digitalit** [quasarframework/quasar-ui-qmediaplayer#224]
I now the link to the movie has to be put in data/sources/src but i need to get the movie link from a computed property that changes movie link on clicking "a next movie button".

Ot works fine with q-video but i would rather use qmp to get more features.

Code in template:
` <q-video
                  :ratio="16/9"
                  :src="this.movieLink"
                />`

code in computed:
`movieLink () {
      let useLink = ''
      if (this.showPc.movies && this.showPc.movies.length && this.showPc.movies[0].movie_file !== 'undefined') {
        useLink = this.videoLink + this.showPc.movies[0].movie_file
      }
      return useLink
    }`

Please tell me this is doable with qmp also :)

videoLink is just a .enf that gives the standard path on the server that movie file is uploaded.

showPc is the presentationcontentpage that changes when stepping to next.

It can only be one movie on one showPc so i don't want this list of movies i see in some examples for data content.

I would like my presentationcontentpage to jave this in data:

`sources: [
        {
          :src: 'this.movieLink',
          :type: 'this.showPc.movies[0].movie_type'
        }
      ]`

And the data must be able to change stepping to next movie presentation page

I hope you get it.

Thank you

**Comment by hawkeye64** [comment]
Having `this.movie` is incorrect. It would just be `movie`

When the HTML of the template is compiled by Vue, it's already part of "this". 
So your above code is the same as `this.this.movieLink`

For QMediaPlayer, you also have `source` property.
You don't need to use `sources` unless you have multiple types of the same video
