### ISSUE TITLE
Mobile poster won't use configured one

### ISSUE THREAD

**Issue by AdrianLeeElder** [quasarframework/quasar-ui-qmediaplayer#229]
The poster loads perfectly fine on desktop. On mobile, I get this placeholder poster with a big black play button.

![image](https://user-images.githubusercontent.com/4062150/110261372-fe5bca00-7f7d-11eb-9fd1-c0ca9295e115.png)

Is there a way to show either the poster or at least show the first frame of the video?

**Comment by hawkeye64** [comment]
QMediaPlayer is just a wrapper around the HTML 5 media player provided by a browser. Each browser may have slight variations and/or behaviors. As in, if you don't provide a poster, then it will.

As for showing first frame, you can start at a point in time as in this example: https://quasarframework.github.io/quasar-ui-qmediaplayer/examples#title-Video---Start-time

As far as the poster not being displayed, can you specify which browser on what OS? And, perhaps make a codepen showing this issue? https://codepen.io/Hawkeye64/pen/WNNgdYa

**Comment by LiamKarlMitchell** [comment]
poster="images/transparent1x1.png"

Image 1 x 1 px transparent png.
![transparent1x1](https://user-images.githubusercontent.com/1968109/117560151-61352300-b0df-11eb-8f4f-5235bf4fdc20.png)

**Comment by hawkeye64** [comment]
@LiamKarlMitchell Yes, use the `no-video` property to force audio only

**Comment by LiamKarlMitchell** [comment]
Thanks @hawkeye64 but `no-video` did not appear to work for me and my type is already audio tried on Android Studio Emulator and on a real phone.

https://github.com/ionic-team/capacitor/discussions/3510
Found that we can also use the code snippet from one of the solutions here in the MainActivity.java to get rid of it which could be good to know for those loading video for before the poster image has loaded.
