### ISSUE TITLE
Support for Quasar V2

### ISSUE THREAD

**Issue by bernhardh** [quasarframework/quasar-ui-qmediaplayer#240]
Are there plans to support Quasar V2? Currently I get 

` Extension(@quasar/qmediaplayer): is not compatible with quasar v2.0.0-beta.13. Required version: ^1.5.0`

**Comment by hawkeye64** [comment]
@bernhardh Yes, but I am concentrating on QCalender at the moment.

**Comment by iohzrd** [comment]
Any eta perchance?

**Comment by hawkeye64** [comment]
I am currently working on it, but I am on vacation all next week, so will be slightly delayed.

**Comment by hawkeye64** [comment]
Closing this as QMediaPlayer v2.0.0-alpha.1 with Quasar v2 and Vue v3 support
https://github.com/quasarframework/quasar-ui-qmediaplayer/releases/tag/v2.0.0-alpha.1
