### ISSUE TITLE
Add streaming support (HLS, DASH)

### ISSUE THREAD

**Issue by blaspix-tech** [quasarframework/quasar-ui-qmediaplayer#243]
Currently, the player doesn't support live streaming.
Maybe this VideoJS extension can help: https://github.com/videojs/http-streaming

**Comment by hawkeye64** [comment]
The component is just a wrapper around the HTML5 media element. Live streaming would use WebRTC technologies.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement

**Comment by blaspix-tech** [comment]
So, can you add an example in the documentation please?

**Comment by hawkeye64** [comment]
This component doesn't do WebRTC. Here are some JavaScript repos that do: https://github.com/search?l=JavaScript&q=webrtc&type=Repositories

**Comment by blaspix-tech** [comment]
Ok thanks @hawkeye64 , really unfortunate that it is not supported on this player.
