### ISSUE TITLE
Issue with fullscreen when inside QPage

### ISSUE THREAD

**Issue by thexeos** [quasarframework/quasar-ui-qmediaplayer#278]
When **QMediaPlayer** is a descendant of `<q-page>,` then fullscreen view is very likely to be broken.

![image](https://user-images.githubusercontent.com/2260539/124370361-b1a7a780-dc6e-11eb-9945-4d4f2f4bb64e.png)

This is "by design" behavior on all browsers. `<q-page>` has non-empty CSS `transform` applied, as well as `will-change: transform`. Both trigger the creation of a new stacking context and a containing block. As a result, `position: fixed` is no longer calculated relative to the viewport, but relative to the containing block. You can see on the screenshot above that even though `left: 0` is used, the actual bounding box of the `<q-media-player>` element starts where `<q-page>` element starts.

The solution is to enter the fullscreen mode with `<q-media-player>` element, instead of `<html>` (default).

I fixed it by changing

https://github.com/quasarframework/quasar-ui-qmediaplayer/blob/254ffac280e4549f68fa573e1a5f11539f6aabd1/ui/src/components/QMediaPlayer.js#L719

to

    this.$q.fullscreen.request(this.$refs.media.parentNode)

Please, let me know if the use of `<html>` as `fullscreenElement` was intentional.

[1] [https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/](https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/)

**Comment by hawkeye64** [comment]
Fixed in v1.3.1
