### ISSUE TITLE
QMedia Player - Branch next not working

### ISSUE THREAD

**Issue by Sell24** [quasarframework/quasar-ui-qmediaplayer#297]
I am not sure what I am doing wrong here but I have installed the next branch as indicated in the first alpha release notes

`quasar ext add @quasar/qmediaplayer@next`

From there I copied verbatim the example code for "VideoBasic" found here: 
[https://github.com/quasarframework/quasar-ui-qmediaplayer/blob/next/docs/src/examples/VideoBasic.vue](url)

```javascript
  
<template>
  <div class="q-pa-md">
    <q-media-player
      type="video"
      :sources="sources"
    />
  </div>

</template>

<script>
import { defineComponent } from 'vue'
import { QMediaPlayer } from '@quasar/quasar-ui-qmediaplayer'
import '@quasar/quasar-ui-qmediaplayer/src/QMediaPlayer.sass'

export default defineComponent({
  name: 'VideoBasic',
  components: {
    QMediaPlayer
  },
  setup () {
    const sources = [
      {
        src: 'http://www.peach.themazzone.com/durian/movies/sintel-2048-surround.mp4',
        type: 'video/mp4'
      }
    ]
    return {
      sources
    }
  }
})
</script>
```

However I am getting the following warning and errors:

![image](https://user-images.githubusercontent.com/16975650/130303664-a1aff583-69ee-4192-9085-1c29497625ed.png)
![image](https://user-images.githubusercontent.com/16975650/130303683-89725105-c4e6-4260-8460-b43a1e166f3d.png)
![image](https://user-images.githubusercontent.com/16975650/130303697-f24e4202-35e7-474f-b4be-14b32cd94ff9.png)

Is there some setup I am missing in the 2.0 alpha to get it to work?

Just to confirm I have tried <q-video> with the same URL and it works.

**Comment by hawkeye64** [comment]
Just something to note here, if you added the app-extension via Quasar, then it handles the boot file for you and the import of the sass file.

I did the following:

quasar create media-test
cd media-test
quasar ext add @quasar/qmediaplayer@next

then in src/pages/Index.vue, I replace the contents with this:

```html
<template>
  <q-page class="flex flex-center">

    <q-media-player
      type="video"
      :sources="sources"
      style="max-width: 800px; width: 100%;"
    />
  </q-page>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'PageIndex',
  setup () {
    const sources = [
      {
        src: 'http://www.peach.themazzone.com/durian/movies/sintel-2048-surround.mp4',
        type: 'video/mp4'
      }
    ]
    return {
      sources
    }
  }
})
</script>
```

then,

quasar dev

The output:

![image](https://user-images.githubusercontent.com/10262924/130683235-e321680d-c483-4d4b-ac29-5ee27775ad91.png)

I am closing this ticket, because the steps are correct. But, obviously, your system has an issue.

I am curious to know if you have overridden any quasar packages, by adding them into your package.json, instead of using the pinned ones from @quasar/app?

Show the output of your `quasar info` and your dependencies and devDependencies from your package.json.

**Comment by hawkeye64** [comment]
I am also really curious where this is coming from?
![image](https://user-images.githubusercontent.com/10262924/130683851-66b20152-f4b2-4889-afb0-51999575b441.png)

**Comment by Sell24** [comment]
I can agree with you that it is probably a system issue. Here is the `quasar info` you requested. 

    Operating System - Windows_NT(10.0.19043) - win32/x64
     NodeJs - 14.16.0

     Global packages 
      NPM - 6.14.11
      yarn - Not installed
      @quasar/cli - 1.1.3 
      @quasar/icongenie - 2.4.0
      cordova - Not installed

      Important local packages 
      quasar - 2.0.4 -- Build high-performance VueJS user interfaces (SPA, PWA, SSR, Mobile and Desktop) in record 
      time
      @quasar/app - 3.1.0 -- Quasar Framework local CLI
      @quasar/extras - 1.10.11 -- Quasar Framework fonts, icons and animations
      eslint-plugin-quasar - Not installed
      vue - 3.2.4 -- The progressive JavaScript framework for buiding modern web UI.
      vue-router - 4.0.11 -- > This is the repository for Vue Router 4 (for Vue 3)
      vuex - 4.0.2 -- state management for Vue.js
      electron - Not installed
      electron-packager - Not installed
      electron-builder - Not installed 
      @babel/core - 7.15.0 -- Babel compiler core.
      webpack - 5.51.1 -- Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jsx, es7, css, less, ... and your custom stuff.
      webpack-dev-server - 4.0.0 -- Serves a webpack app. Updates the browser on changes.
      workbox-webpack-plugin - Not installed
      register-service-worker - 1.7.2 -- Script for registering service worker, with hooks
      typescript - 4.2.2 -- TypeScript is a language for application scale JavaScript development
      @capacitor/core - Not installed
      @capacitor/cli - Not installed
      @capacitor/android - Not installed
      @capacitor/ios - Not installed

      Quasar App Extensions
         @quasar/quasar-app-extension-qmediaplayer - 2.0.0-alpha.2 -- A Quasar App Extension for @quasar/quasar-ui-qmediaplayer
`

Something must have gotten messed up because when I remove the import of Q-Player from the code, it cannot find it when trying to view.

![image](https://user-images.githubusercontent.com/16975650/130784662-6c24bb93-4ff1-4661-b6d1-d2ffe747e878.png)

However when I put them back in it works. 

Just to note, I did update to the latest releases of the quasar from 4 days ago before trying again so maybe that fixed it? 

Anyway I dont want to waste any more of your time since it does work unless you want to pursue why I need to have those imports in order to make it work. However as I mentioned the examples have this.

![image](https://user-images.githubusercontent.com/16975650/130786231-5f0d0bcd-7eb0-41c6-a35b-aa33d98825f3.png)


Thanks for all the support you guys give the community. It really it great.

**Comment by mohanzeal** [comment]
@Sell24 and @hawkeye64 if you inspect the error.. you will understand that the mediaplayer requires "AppFullscreen" plugin.

you simply add below code to your quasar.config.js file to fix the issue.

```
// quasar.config.js
plugins: ["AppFullscreen"],
```
