### ISSUE TITLE
Not working with latest VuejS3 + latest Quasar V2

### ISSUE THREAD

**Issue by renaudham** [quasarframework/quasar-ui-qmediaplayer#316]
**Describe the bug**
I install the extension via Quasar ext add, as required

**Expected behavior**
Should not be rejected on build / dev

**Desktop (please complete the following information):**
 As soon as I start quasar dev, an alert warning in red appears saying that some files are missing.
When I do remove, then I can dev and build normal again..

**Comment by hawkeye64** [comment]
Please append `@next` to package, for Quasar v2, ie:
```
quasar ext add @quasar/qmediaplayer@next
```
