### ISSUE TITLE
Annoying play button icon on android (capacitor)

### ISSUE THREAD

**Issue by lmfmaier** [quasarframework/quasar-ui-qmediaplayer#352]
Hi,

the embedded audio player on android shows an annoying "play button" icon in the background I can't get rid of. I tried to specify a poster  image, used "no-video" - no luck. 

```
<q-media-player
              type="audio"
              no-video
              dark
              dense
              autoplay
              poster="images/poster.png"
              :source="audioSource"
          />
   ```       
          
![image](https://user-images.githubusercontent.com/13540389/145534946-53f5447a-5a20-4051-b42c-c3bdcfbc44ca.png)

**Comment by hawkeye64** [comment]
That's interesting. Doesn't look like they're following the rules as the rest of the controls are not showing up. I presume this is with audio?

Try these:

`no-controls`
Or
`controls=false` or `controls="false"` or `: controls="false"`

Out of that latter, I can't remember which one is best for underlying control when using Vue. Normally, for plain JS, it's the first one.

**Comment by hawkeye64** [comment]
Can you check the element in dev tools and see if it has the attribute `controls` on it?

If you see it, you can do something like this:

```js
const video=getElementsByTagName('video')
function removeControls (video) {
  video.removeAttribute('controls')
}
window.onload=removeControls(video)
```

**Comment by lmfmaier** [comment]
Jeff,

thank you for your reply. I'm afraid the issue has nothing to do with the native controls, these are not visible.

It's a background image, I'm assuming it's the default "poster" image for the html5 video/audio element. It does NOT render in regular Chrome, only in the web view in the android app built with capacitor. I think this can be fixed by providing a poster image, but sadly it's not used when I specify it in the "poster" option:

```
<q-media-player
              type="audio"
              dark
              dense
              autoplay
              poster="images/poster.png"
              :source="audioTrack"
          />
```

The final DOM element looks like this:

```
<video class="q-media--player cursor-inherit" preload="metadata" playsinline="false" autoplay="" src="https://cf-media.sndcdn.com/QaSnV9hZkq58.128.mp3">
<p>To listen to this audio please enable JavaScript and/or consider upgrading to a browser that supports HTML5 audio.</p></video>
```

The "poster" attribute is not on the rendered DOM Element. I guess that's the reason why the android web view shows a default image. This is also noticable when I embed Youtube-IFrames, the background image shortly appears until the actual poster image or first video frame is loaded.

So I think it's an issue in q-media-player since it doesn't attach the poster attribute to the html5 video element. Maybe because ```type="audio"```? The image is in the "public/images" folder in my quasar project.

I'm using the vue3/Quasar2 version btw.

**Comment by lmfmaier** [comment]
I just checked the QMediaPlayer source and it turns out the poster attribute is indeed not applied to the html5 video element when using ```type="audio"``` which will lead to the said behaviour in the android web view

**Comment by hawkeye64** [comment]
Thanks for diving into this. I'll look into it further when I'm able to get onto my computer. It's really early here right now, everyone else is still in bed. :)

**Comment by hawkeye64** [comment]
@lmfmaier Also, what version are you using?

**Comment by lmfmaier** [comment]
> @lmfmaier Also, what version are you using?

Quasar 2.3.4, QuasarMediaPlayer 2.0.0-beta3

**Comment by hawkeye64** [comment]
Let me know if this release fixed it for you.

**Comment by lmfmaier** [comment]
This fixed my problem, thank you very much. The poster image is now applied correctly and the default poster image in the android web view is no longer visible.

**Comment by hawkeye64** [comment]
Good to hear. I'll close this issue then. I wasn't sure if the fix would directly resolve your issue.
