### ISSUE TITLE
el.className.startsWith is not a function

### ISSUE THREAD

**Issue by nseb** [quasarframework/quasar-ui-qmediaplayer#353]
I have an error with basic player : 

el.className.startsWith is not a function
    at __getParentEl (index.esm.js?fcb4:1128)
    at __showControlsIfValid (index.esm.js?fcb4:1136)
    at __mouseMoveAction

**Comment by hawkeye64** [comment]
@nseb Can you please provide your templated code?
This shouldn't happen, and as you can see, it doesn't happen to the examples?
Are you doing any sort of manipulation on the element?

**Comment by hawkeye64** [comment]
Basically, I want to know how to re-create this issue. Can you make a CodePen?

**Comment by hawkeye64** [comment]
Fixed in 2.0.0-beta.6
