### ISSUE TITLE
Requires AppFullscreen plugin.

### ISSUE THREAD

**Issue by digitalextremist** [quasarframework/quasar-ui-qmediaplayer#357]
Issue documented on `discord` and resolved manually:

* https://discord.com/channels/415874313728688138/806171748046733332/974552205241765908

**To Reproduce**
1. Follow the instructions for installation with `2.0.0-beta.6` but do not have `AppFullscreen` in your environment
2. Use `<q-media-player />` at all with even the simplest arguments such as `type='audio' source='/path.mp3`
3. There will be a radical death spiral

**Expected behavior**
1. Load player and have ready to press `play`

**Screenshots**
![image](https://user-images.githubusercontent.com/21095/168223901-6f2f17fb-4677-47e2-aa63-7ef5cea6f470.png)

Before this:
* [Vue warn]: Unhandled error during execution of watcher getter
* [Vue warn]: Unhandled error during execution of setup function 
* [Vue warn]: Unhandled error during execution of scheduler flush. This is likely a Vue internals bug.

**Desktop:**
 - OS: Mint Linux
 - Browser: Brave
 - Version: V1.38.115

**Additional context**
The section that failed and started death spiral was:

```js
watch(() => $q.fullscreen.isActive, val => {
  // user pressed F11/ESC to exit fullscreen
  if (!val && __isVideo.value && state.inFullscreen) {
    exitFullscreen();
  }
});
```

That prompted following these instructions:

* https://quasar.dev/quasar-plugins/app-fullscreen#installation

That plugin being in the environment solves the problem, so somehow this is not going into effect:

* https://github.com/quasarframework/quasar-ui-qmediaplayer/blob/eb0bc001ec226d04fe7d61d11f05d6220b5ed9ca/app-extension/src/index.js#L18

**Comment by hawkeye64** [comment]
Definitely will have to figure out what is going on. This was working.

For reference: https://github.com/quasarframework/quasar-ui-qmediaplayer/blob/next/app-extension/src/index.js#L20

**Comment by digitalextremist** [comment]
@hawkeye64 a wrinkle to add here which probably cracks open the case a bit is that I invoked this extension from an extension of my own. For right now, manually adding `AppFullscreen` on my side is working, but for posterity there is likely a real cure. It seems like this component is well setup to be added into extensions.

One thought would be to catch the error and give a discernible message otherwise it is somewhat indecipherable. I could post a patch like that which does not remedy the issue but calls it out, and likely without much overhead.

**Comment by hawkeye64** [comment]
App Extensions cannot call another app extension. This is why the UI kit was created. You can have an app extension with UI, but if it needs to reference another app-extension, it can only do so via the UI part.

ie: the `quasar-ui-*` can be in the dependencies.

**Comment by digitalextremist** [comment]
Gotcha @hawkeye64. Thanks for spelling that out. I wondered, and this likely means I need to break out the `app` and `ui` elements of my extensions. Hmmm. Well then, this is my bad. Closing per my side being wrong.
