### ISSUE TITLE
Could we have a poster for an audio 

### ISSUE THREAD

**Issue by bebekar** [quasarframework/quasar-ui-qmediaplayer#78]
The only audio display could have a poster image/ svg to make it look beautiful 
the controls could be switched able/disable
The big button is great for control play/pause

**Comment by hawkeye64** [comment]
Agreed. If playing a tracklist (done in dev land), it'd be nice to show the album cover of the song being played. Unfortunately, I am really bogged down at the moment, so this will have to wait.

**Comment by hawkeye64** [comment]
@bebekar I have been thinking about this. I think the best thing to do is wrap the media player in a component that provides this functionality (separation of concerns). Basically, do it in dev-land. You can then share your wrapper component with others. For me, keeping the media player component less opinionated as much as possible is better so that others can use their own creativity instead of being forced one way or another.

**Comment by bebekar** [comment]
What is the difference between <video> and <audio>? nothing! video is big bro, that's it. 

Forget the audio tag all together for a moment. 
play an audio in the video tag, maintain mime type  
add a poster too 
add vtt too

job done. would love your comments

**Comment by hawkeye64** [comment]
@bebekar My friend, you are incorrect -- well, sort of. The <video> and <audio> are different. Vieo use [HTMLAudioElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement) and audio uses [HTMLAudioElement](https://developer.mozilla.org/en- US/docs/Web/API/HTMLAudioElement). Granted, I use the HTMLAudioElement for both audio/video in QMediaPlayer. So, you can probably pass "poster" property and it will work -- briefly.
The poster is like a loading element/bar/icon, etc. It is displayed until the video is ready to play.
I think what you are talking about is to just display an image above for the duration of the audio, which is not how "poster" works.

> HTMLVideoElement.poster
> Is a DOMString that reflects the poster HTML attribute, which specifies an image to show while no video data is available.

Quoted from : https://developer.mozilla.org/en-US/docs/Web/API/HTMLVideoElement

**Comment by bebekar** [comment]
You are right, about the tag.
