### ISSUE TITLE
 [Vue warn]: Error in mounted hook: "TypeError: Cannot set property 'controls' of undefined" in the SSR

### ISSUE THREAD

**Issue by raybest** [quasarframework/quasar-ui-qmediaplayer#86]
**Describe the bug**
```html
      <q-no-ssr>
          <q-media-player
            ref="myPlayer"
            type="video"
            :source="videoUrl"
            no-controls
          />
      </q-no-ssr>
```
**To Reproduce**
1.  quasar dev -m ssr 
2. [Vue warn]: Error in mounted hook: "TypeError: Cannot set property 'controls' of undefined"

but, not error in the spa

**Desktop (please complete the following information):**
 - OS: mac os
 - Browser chrome

**Comment by hawkeye64** [comment]
@raybest Your fix is to use `<q-no-ssr>`? I am not sure I fully understand the issue. Only happens in SSR mode?

**Comment by hawkeye64** [comment]
You never did say what version of QMediaPlayer this was. I suspect it's an older version where this problem was already resolved.
To upgrade:
```
quasar upgrade -i
```
